all: connect4.exe driverc4.com

connect4.exe: connect4.obj
	tlink /v connect4.obj

connect4.obj: connect4.asm
	tasm /zi connect4.asm

driverc4.com: driverc4.obj
	tlink /t /v driverc4.obj

driverc4.obj: driverc4.asm
	tasm /zi driverc4.asm


clean:
	del connect4.obj
	del connect4.map
	del connect4.exe
	del driverc4.obj
	del driverc4.map
	del driverc4.com
