all: connect4.exe driver_c4.com

connect4.exe: connect4.obj
	tlink /v connect4.obj

connect4.obj: connect4.asm
	tasm /zi connect4.asm

driver_c4.com: driver_c4.obj
	tlink /t /v driver_c4.obj

driver_c4.obj: driver_c4.asm
	tasm /zi driver_c4.asm


clean:
	del connect4.obj
	del connect4.map
	del connect4.exe
	del driver_c4.obj
	del driver_c4.map
	del driver_c4.com
